# Py Boxes

## Module: datetime

In [ ]:
import datetime

In [ ]:
# Mengambil date saat kode ini dijalankan
today = datetime.datetime.now()
print(today)
today_2 = datetime.date.today()
print(today_2)

2023-05-03 01:52:36.395769
2023-05-03


In [ ]:
# melihat tipe data
print(type(today))
print(type(today_2))

<class 'datetime.datetime'>
<class 'datetime.date'>


In [ ]:
# fungsi yang ada pada datetime

# mengubah bentuk dari date menjadi string
# dapat mengecek format yang diingan pada dokumen python strftime format
today.strftime('%d-%m-%Y')

'03-05-2023'

In [ ]:
today.strftime('%A, %d %B %Y')

'Wednesday, 03 May 2023'

In [ ]:
# mengambil part dari date
year = today.year
month = today.month
day = today.day

print(f'Hari ini tahun {year} bulan {month} tanggal {day}')

Hari ini tahun 2023 bulan 5 tanggal 3


In [ ]:
# membuat objek date
tanggal_lahir = datetime.datetime(2002, 3, 26)
print(tanggal_lahir)

2002-03-26 00:00:00


## Library: Numpy

In [ ]:
# import library
import numpy as np

In [ ]:
# membuat array
x = np.array(50)
y = np.array('Uzumaki Naruto')
bilangan_genap = np.array([2, 4, 6, 8, 10])
bilangan_ganjil = np.array([1, 3, 5, 7, 9])
print(bilangan_ganjil)
print(bilangan_genap)

[1 3 5 7 9]
[ 2  4  6  8 10]


In [ ]:
# multidimensional array
bilangan = np.array(
    [
       [2, 4, 6, 8, 10],
       [1, 3, 5, 7, 9] #dimesi 2 x 5 (2 baris dan 5 kolom)
    ]
)
bilangan

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [ ]:
# 3 bisa tapi nanti ada fungsi yang tidak dapat digunakan
nomor = np.array(
    [
       [2, 4, 6, 8],
       [1, 3, 5, 7, 9]
    ]
)
nomor

<ipython-input-26-b0df9e651496>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  nomor = np.array(


array([list([2, 4, 6, 8]), list([1, 3, 5, 7, 9])], dtype=object)

In [ ]:
# perbedaa array dengan list
list_bilangan_genap = [2,  4,  6,  8, 10]

print(list_bilangan_genap * 2) # kalo di kali jadi duplikat
print(bilangan_genap * 2) # kalo di array jadinya setiap elemennya yang dikali dua

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]
[ 4  8 12 16 20]


In [ ]:
print(list_bilangan_genap)
print(bilangan_genap + 2)

[2, 4, 6, 8, 10]
[ 4  6  8 10 12]


In [ ]:
# Operasi array
nilai_mahasiswa = np.array([90, 97, 50, 45, 80, 86, 77, 100, 20])
list_nilai_mahasiswa = [90, 97, 50, 45, 80, 86, 77, 100, 20]

In [ ]:
print(np.sum(nilai_mahasiswa))
print(sum(list_nilai_mahasiswa))

645
645


In [ ]:
print(np.min(nilai_mahasiswa))
print(sum(list_nilai_mahasiswa))

20
645


In [ ]:
print(np.mean(nilai_mahasiswa))
# print(mean(list_nilai_mahasiswa))

71.66666666666667


In [ ]:
print(np.median(nilai_mahasiswa))
# print(mean(list_nilai_mahasiswa))

80.0


In [ ]:
print(np.log10(nilai_mahasiswa))

[1.95424251 1.98677173 1.69897    1.65321251 1.90308999 1.93449845
 1.88649073 2.         1.30103   ]


In [ ]:
# mengubah dimensi array
nilai_mahasiswa # (1 x 9)
nilai_mahasiswa.reshape(3,3)

array([[ 90,  97,  50],
       [ 45,  80,  86],
       [ 77, 100,  20]])

In [48]:
# Challenge time
nilai = np.array(
    [
        [80, 87, 91],
        [77, 65, 75],
        [59, 60, 47]
    ]
)

print(nilai)
# mengubah array menjadi 1 dimensi
print(f'array 1 dimensi: {nilai.reshape(1, 9)}')

# kalo kita gatau datanya ada berapa bisa menggunakan reshape seperti ini
print(f'array 1 dimensi (-1): {nilai.reshape(-1)}')

# cek mean lebih besar dari median?
mean = np.mean(nilai)
median = np.median(nilai)

print(f'mean: {mean}')
print(f'median: {median}')
print(f'mean > median: {mean > median}')


[[80 87 91]
 [77 65 75]
 [59 60 47]]
array 1 dimensi: [[80 87 91 77 65 75 59 60 47]]
array 1 dimensi (-1): [80 87 91 77 65 75 59 60 47]
mean: 71.22222222222223
median: 75.0
mean > median: False


# Programming Basic
## Conditional statment

In [51]:
# implementasi 1 kondisi
current_status = 'on-delivery'
barang_diterima = True

if barang_diterima == True:
  current_status = 'delivered'

print(current_status)

delivered


In [56]:
# implementasi 2 kondisi
x = 15

if x > 5:
  print('x lebih besar dari 5')
else:
  print('x tidak lebih besar dari 5')

x lebih besar dari 5


In [59]:
# implementasi 3 kondisi
x  = 100

if x > 10:
  print('x lebih besar dari 10')
elif x == 10:
  print('x sama dengan 10')
else:
  print('x lebih kecil dari 10')

x lebih kecil dari 10


In [62]:
# data nilai 
nilai = [90, 85, 55, 47, 87, 90, 65]

# ingin mengklasifikasikan rata - rata dari nilai tersebut
# jika rata - rata >= 90 maka rapot = 'A'
# jika rata - rata >= 80 maka rapot = 'B'
# jika rata - rata >= 70 maka rapot = 'C'
# jika rata - rata >= 60 maka rapot = 'D'
# # jika rata - rata < 60 maka rapot = 'E'

mean = sum(nilai) / len(nilai)
print(f'nilai rata - rata: {mean}')

if mean >= 90:
  print('nilai raport: A')
elif mean >= 80:
  print('nilai raport: B')
elif mean >= 70:
  print('nilai raport: C')
elif mean >= 60:
  print('nilai raport: D')
else:
  print('nilai raport: E')

nilai rata - rata: 74.14285714285714
nilai raport: C


In [63]:
# jika dijadikan array
nilai = np.array(nilai)
mean = np.mean(nilai)
print(f'nilai rata - rata: {mean}')

if mean >= 90:
  print('nilai raport: A')
elif mean >= 80:
  print('nilai raport: B')
elif mean >= 70:
  print('nilai raport: C')
elif mean >= 60:
  print('nilai raport: D')
else:
  print('nilai raport: E')

nilai rata - rata: 74.14285714285714
nilai raport: C


In [65]:
# Nested IF
prefered_genre = 'anime'
wacth_ads = True

if prefered_genre == 'drama':
  if wacth_ads:
    service = 'service A (with ads)'
  else:
    service = 'service B (no ads)'
elif prefered_genre == 'action':
  if wacth_ads:
    service = 'service C (with ads)'
  else:
    service = 'service D (no ads)'
else:
  service = 'service e'

print(f'preferd genre: {prefered_genre}')
print(f'watch ads: {wacth_ads}')
print(f'streaming service: {service}')

preferd genre: anime
watch ads: True
streaming service: service e


In [66]:
# ternary operator / one line condition statment
age = 60

discount_eligible = 'Yes' if age >=60 else 'No'

print(f'age: {age} is eligible for discount: {discount_eligible}')

age: 60 is eligible for discount: Yes


In [70]:
# number = 42
# gunakan one line conditional untuk menentukan number itu genap atau ganjil

number = 42

bilangan = 'genap' if number % 2 == 0 else 'ganjil'

print(f'bilangan {number} merupakan bilangan {bilangan}')

bilangan 42 merupakan bilangan genap


In [73]:
temp = int(input('masukkan nilai temperature dalam celcius: '))

if temp < 0:
  classification = 'Freezing'
elif temp < 10:
  classification = 'Cold'
elif temp < 20:
  classification = 'Mild'
elif temp < 30:
  classification = 'Warm'
else:
  classification = 'Bekasi'

print(f'{temp}C is {classification}')

masukkannilai temperature dalam celcius: 35
35C is Bekasi


In [79]:
# challenge Time
age = int(input('Masukkan umur: '))
genre = input('Pilih genre yang disukai (action/romantis): ').lower()
service = input('Bersedia menonton iklan (Ya/Tidak)? ').lower()

if service == 'ya':
  recomendation = 'Layanan E'
elif age < 18:
  if genre == 'action':
    recomendation = 'Layanan A'
  elif genre == 'romantis':
    recomendation = 'Layanan B'
  else:
    recomendation = 'Layanan E'
else:
  if genre == 'action':
    recomendation = 'Layanan C'
  elif genre == 'romantis':
    recomendation = 'Layanan D'
  else:
    recomendation = 'Layanan E'


print(f'Rekomedasi layanan untuk genre favorit Anda adalah {recomendation}')

Masukkan umur: 40
Pilih genre yang disukai (action/romantis): horor
Bersedia menonton iklan (Ya/Tidak)? ya
Rekomedasi layanan untuk genre favorit Anda adalah Layanan E
